version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - JWT_SECRET=supersecret
    volumes:
      - ../backend:/app
    restart: always

volumes:
  mongo_data: